### ISSUE TITLE
Add POI Radio support to StakeSquid docker-compose stack

### ISSUE THREAD

**Issue by chriswessels** [graphops/poi-radio#1]
**Problem statement**
There's manual work required to add the POI Radio to StakeSquid's docker-compose stack

**Expectation proposal**
We should submit a pull request to their repo to include the POI Radio as part of the default indexing stack, alongside any doc updates that are required

**Alternative considerations**
None

**Additional context**
None

**Comment by axiomatic-aardvark** [comment]
Is this post-MVP?
