### ISSUE TITLE
[FRQ] Rescope POI radio to Subgraph radio

### ISSUE THREAD

**Issue by hopeyen** [graphops/poi-radio#102]
**Problem statement**
We would like to expand the POI radio to gossip messages on a Subgraph level, instead of only nPOI for each subgraphs. We assume that Indexers can simply run a single instance of Subgraph Radio and be able to track all gossips such as nPOIs and deployment health, and potentially versioning of setups. 

**Expectation proposal**
Rough outline
- Rename relevant namespaces
- Update `RadioPayloadMessage` to be specifically `ProofOfIndexingMessage`
- Configurable message types to turn on with possible values. Start off with `ProofOfIndexingMessage` and `DeploymentHealthMessage`
- Add struct, construction, parsing, and comparison mechanism for `DeploymentHealthMessage`
- New `radio_msg_handler` to match generalized message types
  - compare benefits: 1. generalized storage into 1 array, same validation processes, sorted at attestation; 2. separate storage for each message type, modular validation process (not necessary as indexer identity requirement is the same), no sorting at attestation
- New local_attestations struct to consist fields for all message types
- New `message_send` for generalized message types
- New `message_compare` for generalized message types

**Alternative considerations**
open to suggestions and ideas

**Comment by axiomatic-aardvark** [comment]
1. Rename all existing namespaces to "POI Radio"
2. Create new structure - `DeploymentHealthMsg`
3. Mock new structure
- sending (raw waku, see e2e `sender` crate)
- parsing
- comparison (handling? cadence - periodically or event based?)
4. Message handler (generic)
- pattern match on waku Signal to determine what type of GraphcastMessage
5. New storages
- New data storage (new hashmap) similar to local_attestations (sth like `local_deployment_health_statuses`)
- Sth similar to `remote_messages` (current one renamed to `remote_poi_msgs` - should be done in step 1. and new one sth like `remote_deployment_health_statuses`)

Open questions
- document the value for Indexers from having `DeploymentHealthMsg`
- periodic vs event-based messaging
- do we package both message types into one or have them separate

**Comment by axiomatic-aardvark** [comment]
Issue rescoped https://github.com/graphops/poi-radio/issues/177
