### ISSUE TITLE
Fantom subgraphs throw an "unsupported network" warning

### ISSUE THREAD

**Issue by axiomatic-aardvark** [graphops/poi-radio#106]
**Describe the bug**
@stake-machine has a `Fantom` subgraph on testnet and the Radio is showing this warning:
```bash
  2023-04-21T09:22:24.166410Z  WARN graphcast_sdk: err_msg: "Subgraph is indexing an unsupported network fantom, please report an issue on https://github.com/graphops/graphcast-rs"
    at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/graphcast-sdk-0.1.0/src/lib.rs:159
```

**Expected behavior**
The Radio should support fantom subgraphs, since `Fantom` is in out supported networks list [here](https://github.com/graphops/graphcast-sdk/blob/60074d8ae3ab47c1e96391012cf4df35d2db62c4/src/networks.rs#L24).

**Comment by akme** [comment]
Here is the problem 
```       
 // Fantom: ~2-3 seconds
        Network {
            name: NetworkName::from_string("optimism"),
            interval: 100,
        },
```
https://github.com/graphops/graphcast-sdk/blob/60074d8ae3ab47c1e96391012cf4df35d2db62c4/src/networks.rs#L118-L126
