### ISSUE TITLE
[Feat.Req] Generate an ephemeral test topic

### ISSUE THREAD

**Issue by AbelTedros** [graphops/poi-radio#126]
**Problem statement**

**Expectation proposal**

**Alternative considerations**

**Additional context**
Generate an ephemeral test topic so that the test instances only send/receive messages on it, in order for the tests to be fully deterministic and not get mixed up with other test instances that might be running at the same time somewhere else. Currently the test topic is just "poi-radio-test".

**Comment by axiomatic-aardvark** [comment]
this will be done as part of https://github.com/graphops/poi-radio/issues/64
