### ISSUE TITLE
[Feat.Req] Add link to docs in README.md

### ISSUE THREAD

**Issue by matthewdarwin** [graphops/poi-radio#137]
**Problem statement**
Allow the docs to be discoverable when starting from this github repo.  

**Expectation proposal**
Add a link to https://docs.graphops.xyz/graphcast/radios/poi-radio

**Alternative considerations**
Do nothing. Make me fumble around.

**Additional context**
none

**Comment by jhjhjh94** [comment]
According to this https://docs.graphops.xyz/graphcast/radios/poi-radio

If possible please provide address or add Arbitrum Registry URL to call setGraphcastIDFor.

**Comment by hopeyen** [comment]
> To be clear, you can click the docs button I highlighted with a blue box in the screenshot below.

The doc link is also here, but let us know if there are more preferred places.
![Screenshot 2023-05-15 at 9 52 42 AM](https://github.com/graphops/poi-radio/assets/60078528/ebe7a9c1-a4f0-4505-95b2-d5d59ad27588)

**Comment by matthewdarwin** [comment]
I totally skip over the batches when reading.  I'm looking for "docs" section.
