### ISSUE TITLE
Rescope POI Radio to Subgraph Radio

### ISSUE THREAD

**Issue by axiomatic-aardvark** [graphops/poi-radio#177]
**Problem statement**
We would like to expand the POI radio to gossip messages on a Subgraph level, instead of only nPOI for each subgraphs. We assume that Indexers can simply run a single instance of Subgraph Radio and be able to track a wide variety of message types and data, related to subgraphs.

Original idea was defined here, but it also described adding `DeploymentHealthMessage`, which was dropped from the scope - https://github.com/graphops/poi-radio/issues/102

**Expectation proposal**
We need to rename every instance of "POI Radio" and generalise some functions and data structures, in order to support different message types in the future. We will not be adding any new message type as part of the work on this Issue, but it will open the door for  such features.

Rough outline and implementation ideas:

- [ ] Rename namespaces
- [ ] Extract generic `RadioPayloadMessage` and separate a specific `ProofOfIndexingMessage`/`POIMessage`
- [ ] Add enum for different message types (with only 1 value for now)
- [ ] Update `radio_msg_handler` to be generic
- [ ] Modular validation process (some message types might not need the indexer validation for instance)
- [ ] Rename local_attestations to something more generic (or keep it but place it within some more generic struct like `local_subgraph_store` for instance)
- [ ] New `message_send` for generalised message types
- [ ] New `message_compare` for generalised message types

**Comment by hopeyen** [comment]
- [x] Rename namespaces https://github.com/graphops/poi-radio/pull/207
- [x] Extract generic `RadioPayloadMessage` and separate a specific `ProofOfIndexingMessage`/`POIMessage` https://github.com/graphops/poi-radio/pull/204
- [x] Update `radio_msg_handler` to be generic https://github.com/graphops/poi-radio/pull/204
- [x] Modular validation process (some message types might not need the indexer validation for instance) [https://github.com/graphops/poi-radio/pull/204]
- [x] New `message_send` for generalised message types [factored to specific type, generic can be written if needed https://github.com/graphops/poi-radio/pull/207]
- [x] New `message_compare` for generalised message types [factored to specific type, generic can be written if needed https://github.com/graphops/poi-radio/pull/207]

Todo later if needed

- Rename local_attestations to something more generic (or keep it but place it within some more generic struct like `local_subgraph_store` for instance)
- Add enum for different message types (with only 1 value for now)

**Comment by hopeyen** [comment]
<3
