### ISSUE TITLE
Add POI Radio support to Launchpad

### ISSUE THREAD

**Issue by chriswessels** [graphops/poi-radio#3]
**Problem statement**
There's manual work required to add the POI Radio to Launchpad

**Expectation proposal**
We should submit a pull request to launchpad to include the POI Radio as part of the default indexing stack, alongside any doc updates that are required

**Alternative considerations**
None

**Additional context**
None

**Comment by hopeyen** [comment]
Moved to https://github.com/graphops/subgraph-radio/issues/11
