### ISSUE TITLE
Improve Slack notifications

### ISSUE THREAD

**Issue by axiomatic-aardvark** [graphops/poi-radio#44]
We should add better structure to the Slack notification messages that are sent when the comparison function in the main loop doesn't return `Ok()`. This should include as much useful information as possible, here's a few points:
- If the POI is diverging, send the list of senders who back that POI along with their stake. Also send info about other peers that have the same POI as the current Radio instance.
- Don't overdo it with notifications, maybe some errors/warnings are not important enough to trigger notifications

Considerations:
I think it would be good to do this issue after we've figured out the one for improving error handling - https://github.com/graphops/poi-radio/issues/10

**Comment by hopeyen** [comment]
closed by #65
