### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by axiomatic-aardvark** [graphops/poi-radio#6]
We should add more integration tests to the POI Radio, this can include checks for:
- first time sender
- attestation conflicts
- ...

Please feel free to suggest more integration test scenarios.

**Comment by hopeyen** [comment]
Some test scenario ideas:
- Stored messages calculated into attestations
   - check for the expected sum amount from the stored messages grouped by POI.
   - check for the expected indexer id list.
- Say `X` indexers are normal, `Y` indexers are malicious.
   - when `sum_stake(X)>sum_stake(Y)` For an indexer in `X`, POI is normal and there’s no conflict,
   - check indexer `Y` receives POI divergence error (depending on how the test is set up, or just use another set of test for the opposite config)
   - when `sum_stake(X)=sum_stake(Y)` indexers in both groups receive divergence error
- block map: `X` indexers are normal, `Y` indexer’s block is delayed. Check that `Y`'s POI is not included in the attestation process
- When there’s multiple topics, check that POIs are separately attested.

**Comment by hopeyen** [comment]
Yay #90 🎉
