### ISSUE TITLE
Add Prometheus metrics to POI Radio

### ISSUE THREAD

**Issue by chriswessels** [graphops/poi-radio#61]
**Problem statement**
We want the Radio to export metrics via Prometheus in order to make visualisation of POI Radio data inside Grafana easy

**Expectation proposal**
As a user, I want to see:
- About my own deployments/indexers
  - **How many of my deployments are being actively crosschecked with other indexers (remotePOIs != 0)**
  - **How many and which of my local deployments are non-consensus POIs**
  - How many indexers are participating across the deployments that the indexer is currently allocated to
- About data integrity in the wider network
  - For subgraphs that I am allocated to(?), **how many nPOI groups exist and what is the total attesting stake per nPOI for the deploy**, total attesting stake per "indexer group hash" (#60)

**Specific metric ideas** (pinch of salt pls)
The POI Radio should export a variety of metrics indicating the state of the system:
- aggregate_attesting_stake_npoi
  - labels: deployment hash, npoi, network, blockNumber
  - value: aggregate attesting stake in GRT
  - use cases: visualising total attesting stake in the network, visualising number of distinct nPOIs per subgraph deployment, visualising attesting stake per deployment or per network
- aggregate_attesting_stake_indexer_group
  - labels: deployment hash, indexerGroupHash, network, blockNumber
  - value: aggregate attesting stake in GRT
  - use cases: visualising total attesting stake in the network, visualising number of attesting groups per subgraph deployment, visualising attesting stake per deployment or per network

**Comment by hopeyen** [comment]
#89 changes merged in #91
