### ISSUE TITLE
[FRQ] Optionally pass in dependencies

### ISSUE THREAD

**Issue by chriswessels** [graphops/poi-radio#74]
**Problem statement**
It is useful to be able to know which dependencies are attached to a given POI attestation. This would help us root cause divergence issues.

**Expectation proposal**
Imagine an Indexer could pass any number of supported dependencies as configuration. If this were a flag, it could take the form:

`--dep <type>:<id>=<uri>`

```
poi-radio --dep postgresql:primary=postgresql://host:5432 --dep chain:mainnet=http://geth:8545
```

For each provided flag, handler logic could be defined for the `type` that allows POI Radio to extract the version. For example, for the `chain` type, the POI radio could call `web3_clientVersion` at the provided `uri` to get the client version. A SQL statement could similarly be executed to get PostgreSQL version.

The resulting dependency information could be attached to POI messages.

**Alternative considerations**
None, but please comment with ideas.

**Comment by hopeyen** [comment]
Do you think it would make sense for all Graphcast message? or specific to POI radio? Could this be only optionally passed in or something required upon radio start-up?

**Comment by hopeyen** [comment]
Moved to https://github.com/graphops/subgraph-radio/issues/9
